---
only: issues
limitPerRun: 30
daysUntilStale: 45
daysUntilClose: 60
exemptLabels:
  - bug
  - In progress
  - planned
  - enhancement
exemptProjects: true
exemptMilestones: true
staleLabel: stale
markComment: >
  Currently WordOps team doesn't have enough capacity to work on this issue.
  We will be more than glad to accept a pull request with a solution to problem described here.
  This issue will be closed after another 60 days of inactivity.
closeComment: >
  This issue has been automatically closed due to extended period of inactivity.
  Please reopen if it is still valid. Thank you for your contributions.
