name: Tests
on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install build-essential
      run: sudo apt-get install build-essential gcc  -y
    - name: Install pipenv
      run: pip3 install -U pipenv
    - name: Install Deps
      run: pipenv install --dev --system
    - name: Launch test
      run: coverage run -m pytest ./  --disable-pytest-warnings
    - name: Coverage
      run: coverage xml
#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v1
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: ./coverage.xml
#        flags: unittests
#        name: codecov-umbrella
#        yml: ./codecov.yml
#        fail_ci_if_error: true
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./coverage.xml
