name: Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install build-essential
      run: sudo apt-get install build-essential gcc  -y
    - name: Install poetry
      run: pip3 install -U poetry
    - name: Install Deps
      run: poetry install
    - name: Build
      run: poetry build
    - name: Publish
      run: poetry publish
      env:
        MYPYPI_USER: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
